from __future__ import annotations

from enum import StrEnum


class AISidecarTaskType(StrEnum):
    DAILY_MARKET_BRIEF = "DAILY_MARKET_BRIEF"
    THEME_BRIEF = "THEME_BRIEF"
    CANDIDATE_BLOCK_RCA = "CANDIDATE_BLOCK_RCA"
    NO_TRADE_RCA = "NO_TRADE_RCA"
    TRADE_REVIEW = "TRADE_REVIEW"
    OPS_INCIDENT_SUMMARY = "OPS_INCIDENT_SUMMARY"
    CODEX_PROMPT_DRAFT = "CODEX_PROMPT_DRAFT"
