from __future__ import annotations

from enum import StrEnum


class DryRunRejectionReason(StrEnum):
    SAFETY_GATE_FAILED = "SAFETY_GATE_FAILED"
    DRY_RUN_DISABLED = "DRY_RUN_DISABLED"
    LIVE_FLAGS_ENABLED = "LIVE_FLAGS_ENABLED"
    STRATEGY_OBSERVATION_MISSING = "STRATEGY_OBSERVATION_MISSING"
    RISK_OBSERVATION_MISSING = "RISK_OBSERVATION_MISSING"
    STRATEGY_NOT_MATCHED = "STRATEGY_NOT_MATCHED"
    RISK_NOT_OBSERVE_PASS = "RISK_NOT_OBSERVE_PASS"
    CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND"
    CANDIDATE_NOT_CONTEXT_READY = "CANDIDATE_NOT_CONTEXT_READY"
    LATEST_TICK_MISSING = "LATEST_TICK_MISSING"
    LATEST_TICK_STALE = "LATEST_TICK_STALE"
    DUPLICATE_DRY_RUN_INTENT = "DUPLICATE_DRY_RUN_INTENT"
    DUPLICATE_DRY_RUN_ORDER = "DUPLICATE_DRY_RUN_ORDER"
    DUPLICATE_DRY_RUN_POSITION = "DUPLICATE_DRY_RUN_POSITION"
    MAX_DAILY_INTENTS_REACHED = "MAX_DAILY_INTENTS_REACHED"
    MAX_ACTIVE_POSITIONS_REACHED = "MAX_ACTIVE_POSITIONS_REACHED"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INVALID_NOTIONAL = "INVALID_NOTIONAL"
    INVALID_SIDE = "INVALID_SIDE"
    ORDER_ROUTING_DISABLED = "ORDER_ROUTING_DISABLED"
    GATEWAY_COMMAND_FORBIDDEN = "GATEWAY_COMMAND_FORBIDDEN"
    OBSERVE_ONLY_PIPELINE = "OBSERVE_ONLY_PIPELINE"
    AI_OUTPUT_NOT_ALLOWED = "AI_OUTPUT_NOT_ALLOWED"
    RCA_OUTPUT_NOT_ALLOWED = "RCA_OUTPUT_NOT_ALLOWED"
    CODEX_PROMPT_NOT_ALLOWED = "CODEX_PROMPT_NOT_ALLOWED"
    SIMULATED_FILL_DISABLED = "SIMULATED_FILL_DISABLED"
    DRY_RUN_ORDER_NOT_FOUND = "DRY_RUN_ORDER_NOT_FOUND"
    DRY_RUN_INTENT_NOT_FOUND = "DRY_RUN_INTENT_NOT_FOUND"
