from __future__ import annotations

from enum import StrEnum


class DryRunIntentStatus(StrEnum):
    CREATED = "CREATED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    CONVERTED_TO_DRY_RUN_ORDER = "CONVERTED_TO_DRY_RUN_ORDER"


class DryRunOrderStatus(StrEnum):
    CREATED = "CREATED"
    SIMULATED_SUBMITTED = "SIMULATED_SUBMITTED"
    SIMULATED_FILLED = "SIMULATED_FILLED"
    SIMULATED_PARTIALLY_FILLED = "SIMULATED_PARTIALLY_FILLED"
    SIMULATED_CANCELLED = "SIMULATED_CANCELLED"
    SIMULATED_REJECTED = "SIMULATED_REJECTED"
    EXPIRED = "EXPIRED"
