from __future__ import annotations

from enum import StrEnum


class CandidateReasonCode(StrEnum):
    CONDITION_ENTERED = "CONDITION_ENTERED"
    CONDITION_EXITED = "CONDITION_EXITED"
    THEME_LEADING_MEMBER = "THEME_LEADING_MEMBER"
    THEME_CO_LEADER_MEMBER = "THEME_CO_LEADER_MEMBER"
    THEME_FOLLOWER_MEMBER = "THEME_FOLLOWER_MEMBER"
    THEME_STATE_LEADING = "THEME_STATE_LEADING"
    THEME_STATE_SPREADING = "THEME_STATE_SPREADING"
    MARKET_TICK_FRESH = "MARKET_TICK_FRESH"
    MARKET_READINESS_READY = "MARKET_READINESS_READY"
    MARKET_READINESS_MISSING = "MARKET_READINESS_MISSING"
    BAR_MISSING = "BAR_MISSING"
    VWAP_MISSING = "VWAP_MISSING"
    THEME_MISSING = "THEME_MISSING"
    SOURCE_STALE = "SOURCE_STALE"
    TICK_STALE = "TICK_STALE"
    SOURCE_EXITED = "SOURCE_EXITED"
    EPISODE_TTL_EXPIRED = "EPISODE_TTL_EXPIRED"
    DUPLICATE_SOURCE_MERGED = "DUPLICATE_SOURCE_MERGED"
    OBSERVATION_BLOCKED = "OBSERVATION_BLOCKED"
    SOURCE_DETECTED = "SOURCE_DETECTED"
    SOURCE_MISSING = "SOURCE_MISSING"
    CONTEXT_READY = "CONTEXT_READY"
    CANDIDATE_CREATED = "CANDIDATE_CREATED"
    THEME_ROTATED_OUT = "THEME_ROTATED_OUT"
