from __future__ import annotations

from enum import StrEnum


class DryRunExitEvaluationStatus(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    DATA_WAIT = "DATA_WAIT"
    HOLD_OBSERVED = "HOLD_OBSERVED"
    EXIT_SIGNAL_OBSERVED = "EXIT_SIGNAL_OBSERVED"
    EXIT_CAUTION_OBSERVED = "EXIT_CAUTION_OBSERVED"
    INVALID_POSITION = "INVALID_POSITION"
    STALE_CONTEXT = "STALE_CONTEXT"


class DryRunExitSignalType(StrEnum):
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT = "TAKE_PROFIT"
    TRAILING_STOP = "TRAILING_STOP"
    MAX_HOLD = "MAX_HOLD"
    DATA_STALE_EXIT_CAUTION = "DATA_STALE_EXIT_CAUTION"
    THEME_WEAKENING = "THEME_WEAKENING"
    RISK_DETERIORATION = "RISK_DETERIORATION"
    STRATEGY_INVALIDATED = "STRATEGY_INVALIDATED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class DryRunExitIntentStatus(StrEnum):
    CREATED = "CREATED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    CONVERTED_TO_EXIT_ORDER = "CONVERTED_TO_EXIT_ORDER"


class DryRunExitOrderStatus(StrEnum):
    CREATED = "CREATED"
    SIMULATED_SUBMITTED = "SIMULATED_SUBMITTED"
    SIMULATED_FILLED = "SIMULATED_FILLED"
    SIMULATED_PARTIALLY_FILLED = "SIMULATED_PARTIALLY_FILLED"
    SIMULATED_CANCELLED = "SIMULATED_CANCELLED"
    SIMULATED_REJECTED = "SIMULATED_REJECTED"
    EXPIRED = "EXPIRED"
