from __future__ import annotations

from enum import StrEnum


class RiskCategory(StrEnum):
    DATA_QUALITY = "DATA_QUALITY"
    MARKET_CONTEXT = "MARKET_CONTEXT"
    THEME_CONTEXT = "THEME_CONTEXT"
    CANDIDATE_CONTEXT = "CANDIDATE_CONTEXT"
    STRATEGY_CONTEXT = "STRATEGY_CONTEXT"
    CHASE_OVERHEAT = "CHASE_OVERHEAT"
    LIQUIDITY_SPREAD = "LIQUIDITY_SPREAD"
    DUPLICATE_COOLDOWN = "DUPLICATE_COOLDOWN"
    PORTFOLIO_PLACEHOLDER = "PORTFOLIO_PLACEHOLDER"
